---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app-flux-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: app-flux
  filterTags:
    pattern: '^prod-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc

