---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app-flux-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: app-flux
  policy:
    semver:
      range: 1.0.x

