---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app-flux
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: ssh://git@github.com/josh-gree/app_flux

