apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: joshgree/app-flux:dev-c068f997abee9282ba0b88941215486f2ee001e0-1676227387 # {"$imagepolicy": "flux-system:app-flux-dev"}
