apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: joshgree/app-flux:dev-278b897ef5a27f8494eaafdb46fb40b55d76c8c6-1676218993 # {"$imagepolicy": "flux-system:app-flux-dev"}
