apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: joshgree/app-flux:dev-a4876af729285dbadb2bf69d12a688f4b9973922-1676218615 # {"$imagepolicy": "flux-system:app-flux-dev"}
