apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: joshgree/app-flux:prod-1a162a427055bb7a4a03988d4d6a04b6197c4519-1676227534 # {"$imagepolicy": "flux-system:app-flux-prod"}
