apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: joshgree/app-flux:prod-d601c704384d8a4b447336b1e77548305ba1c952-1676216731 # {"$imagepolicy": "flux-system:app-flux-prod"}
